<?php
// +----------------------------------------------------------------------
// | ThinkPHP [ WE CAN DO IT JUST THINK ]
// +----------------------------------------------------------------------
// | Copyright (c) 2006~2018 http://thinkphp.cn All rights reserved.
// +----------------------------------------------------------------------
// | Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------
// | Author: liu21st <liu21st@gmail.com>
// +----------------------------------------------------------------------
use think\Route;
//添加路由规则[默认index模块]
Route::get('Welcome/:name','index/welcome/:name');

//Route::domain('lenglian.com','index');
return [
    '__pattern__' => [
        'name' => '\w+',
    ],
    'welcome/user_login'=>'index/welcome/user_login',
    'welcome/user_info'=>'index/welcome/user_info',
    'welcome/user_info_change'=>'index/welcome/user_info_change',
    'welcome/user_password_change'=>'index/welcome/user_password_change',
    'welcome/user_login_out'=>'index/welcome/user_login_out',
    'welcome/run'=>'index/welcome/run',
    'schedule/monitor_latest'=>'index/schedule/monitor_latest',
    'schedule/monitor_save'=>'index/schedule/monitor_save',
    'schedule/station_listing'=>'index/schedule/station_listing',
    'schedule/station_save'=>'index/schedule/station_save',
    'schedule/station_delete'=>'index/schedule/station_delete',
    'schedule/station_group_add'=>'index/schedule/station_group_add',
    'schedule/station_group_delete'=>'index/schedule/station_group_delete',
    'schedule/user_listing'=>'index/schedule/user_listing',
    'schedule/class_listing'=>'index/schedule/class_listing',
    'schedule/monitor_listing'=>'index/schedule/monitor_listing',
    'schedule/class_save'=>'index/schedule/class_save',
    'schedule/schedule_save'=>'index/schedule/schedule_save',
    'schedule/class_delete'=>'index/schedule/class_delete',
    'schedule/schedule_listing'=>'index/schedule/schedule_listing',
    'device/group_listing'=>'index/device/group_listing',
    'device/box_latest'=>'index/device/box_latest',
    'device/box_data'=>'index/device/box_data',
    'device/box_data_page'=>'index/device/box_data_page',
    'device/group_list'=>'index/device/group_list',
    'device/group_save'=>'index/device/group_save',
    'device/group_box_save'=>'index/device/group_box_save',
    'device/box_list'=>'index/device/box_list',
    'device/group_box_clear'=>'index/device/group_box_clear',
    'device/group_delete'=>'index/device/group_delete',
    'device/group_box_save'=>'index/device/group_box_save',
    'device/device_category'=>'index/device/device_category',
    'device/box_save'=>'index/device/box_save',
    'device/box_info'=>'index/device/box_info',
    'device/box_param'=>'index/device/box_param',
    'device/box_param_save'=>'index/device/box_param_save',
    'device/box_op_state'=>'index/device/box_op_state',
    'device/box_op'=>'index/device/box_op',
    'device/box_group_save'=>'index/device/box_group_save',
    'device/main_insert'=>'index/device/main_insert',
    'alarm/alarm_index'=>'index/alarm/alarm_index',
    'alarm/alarm_setting'=>'index/alarm/alarm_setting',
    'alarm/alarm_msg'=>'index/alarm/alarm_msg',
    'alarm/alarm_index_info'=>'index/alarm/alarm_index_info',
    'alarm/alarm_save'=>'index/alarm/alarm_save',
    'alarm/alarm_current'=>'index/alarm/alarm_current',
    'alarm/alarm_history'=>'index/alarm/alarm_history',
    'travel/travel_list'=>'index/travel/travel_list',
    'travel/travel_delete'=>'index/travel/travel_delete',
    'travel/travel_save'=>'index/travel/travel_save',
    'travel/travel_change'=>'index/travel/travel_change',
    'travel/travel_info'=>'index/travel/travel_info',
    'travel/travel_box_save'=>'index/travel/travel_box_save',
    'report/run_time'=>'index/report/run_time',
    'systemlog/log_category'=>'index/systemlog/log_category',
    'systemlog/log_list'=>'index/systemlog/log_list',
    'dept/dept_save'=>'index/dept/dept_save',
    'dept/dept_delete'=>'index/dept/dept_delete',
    'dept/dept_listing'=>'index/dept/dept_listing',
    'dept/user_listing'=>'index/dept/user_listing',
    'dept/user_info'=>'index/dept/user_info',
    'dept/user_save'=>'index/dept/user_save',
    'dept/user_delete'=>'index/dept/user_delete',
    'dept/limit_add'=>'index/dept/limit_add',
    'dept/limit_info'=>'index/dept/limit_info',
    'dept/limit_edit'=>'index/dept/limit_edit',
    'dept/limit_delete'=>'index/dept/limit_delete',
    'dept/limit_list'=>'index/dept/limit_list',
    'dept/role_user'=>'index/dept/role_user',
    'dept/role_list'=>'index/dept/role_list',
    'dept/role_save'=>'index/dept/role_save',
    'dept/role_detail'=>'index/dept/role_detail',
    'dept/role_edit'=>'index/dept/role_edit',
    'dept/role_delete'=>'index/dept/role_delete',
    'dept/role_grouplist'=>'index/dept/role_grouplist',
    'dept/role_group_add'=>'index/dept/role_group_add',
    'dept/role_group_edit'=>'index/dept/role_group_edit',
    'dept/role_group_delete'=>'index/dept/role_group_delete',
    'dept/role_ce'=>'index/dept/role_ce',
    'manual/manual_list'=>'index/manual/manual_list',
    'manual/manual_info'=>'index/manual/manual_info',
    //map 部分
    'map/fence_list'=>'index/map/fence_list',
    'map/fence_info'=>'index/map/fence_info',
    'map/fence_save'=>'index/map/fence_save',
    'map/fence_delete'=>'index/map/fence_delete',
    //end of map
    //手持设备
    /*'waybill/waybill_save'=>'container/waybill/waybill_save',
    'waybill/waybill_detail'=>'container/waybill/waybill_detail',
    'waybill/waybill_list'=>'container/waybill/waybill_list',
    'waybill/waybill_list_page'=>'container/waybill/waybill_list_page',
    'waybill/waybill_delete'=>'container/waybill/waybill_delete',
    'waybill/travel_info_status_save'=>'container/waybill/travel_info_status_save',
    'waybill/travel_info_status_delete'=>'container/waybill/travel_info_status_delete',
    'operation/operation_list_save'=>'container/operation/operation_list_save',
    'operation/operation_list_details'=>'container/operation/operation_list_details',
    'operation/all_operation_list_page'=>'container/operation/all_operation_list_page',
    'operation/operation_list_delete'=>'container/operation/operation_list_delete',
    'operation/box_damage_save'=>'container/operation/box_damage_save',
    'operation/damage_style'=>'container/operation/damage_style',
    'operation/box_damage_details'=>'container/operation/box_damage_details',
    'operation/box_damage_list'=>'container/operation/box_damage_list',
    'operation/delete_img'=>'container/operation/delete_img',
    'operation/delete_box_info'=>'container/operation/delete_box_info',
    'container/app_version'=>'container/container/app_version',
    'container/user_login_info'=>'container/container/user_login_info',
    'container/handle_user_login_out'=>'container/container/handle_user_login_out',*/
    '[hello]'     => [
        ':id'   => ['index/hello', ['method' => 'get'], ['id' => '\d+']],
        ':name' => ['index/hello', ['method' => 'post']],
    ],

];
